# Generated by Django 4.2.7 on 2023-11-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Languageapp', '0002_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='UserNames',
            field=models.CharField(default='student', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='emails',
            field=models.CharField(default='abcd', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
